TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  eval_strategy:  'steps'
  eval_steps: 500
  save_steps: 1000000
  gradient_accumulation_steps: 32  # Increased from 16
  gradient_checkpointing: true     # Add this to save memory
  dataloader_pin_memory: false     # Add this to avoid MPS warning
  fp16: false                      # Don't use fp16 on MPS
  bf16: false                      # Don't use bf16 on MPS
